$(document).ready(function() {
	var answers = [
		"<h2><a href=''>HCI theory explains how we think.</a></h2><p>I'm the Batman. Thwok wallop pow koom zoink twak pok zoink smack zap crack pop zzzip. Thwok bwom vrooaaaa bam pow screeeeam kaboom vroom zap snap twak. Crackle whack boom zap wham tonk wallop bwom whack blam gadzooks. Kerplunk screeeeam koom tonk zap crash bwom screeeeam zzzip bam vroom smack pow. Vroom whack wallop crash kerplunk bwom twak pow bwom crash!</p>",
		"<h2><a href=''>HCI theory helps us understand the meaning of symbols.</a></h2><p>I'm the Batman. Thwok wallop pow koom zoink twak pok zoink smack zap crack pop zzzip. Thwok bwom vrooaaaa bam pow screeeeam kaboom vroom zap snap twak. Crackle whack boom zap wham tonk wallop bwom whack blam gadzooks. Kerplunk screeeeam koom tonk zap crash bwom screeeeam zzzip bam vroom smack pow. Vroom whack wallop crash kerplunk bwom twak pow bwom crash!</p>",
		"<h2><a href=''>HCI theory helps us see the big picture.</a></h2><p>I'm the Batman. Thwok wallop pow koom zoink twak pok zoink smack zap crack pop zzzip. Thwok bwom vrooaaaa bam pow screeeeam kaboom vroom zap snap twak. Crackle whack boom zap wham tonk wallop bwom whack blam gadzooks. Kerplunk screeeeam koom tonk zap crash bwom screeeeam zzzip bam vroom smack pow. Vroom whack wallop crash kerplunk bwom twak pow bwom crash!</p>",
		"<h2><a href=''>HCI theory helps us understand how people work in groups.</a></h2><p>I'm the Batman. Thwok wallop pow koom zoink twak pok zoink smack zap crack pop zzzip. Thwok bwom vrooaaaa bam pow screeeeam kaboom vroom zap snap twak. Crackle whack boom zap wham tonk wallop bwom whack blam gadzooks. Kerplunk screeeeam koom tonk zap crash bwom screeeeam zzzip bam vroom smack pow. Vroom whack wallop crash kerplunk bwom twak pow bwom crash!</p>",
		"<h2><a href=''>HCI theory helps us work together using computers.</a></h2><p>I'm the Batman. Thwok wallop pow koom zoink twak pok zoink smack zap crack pop zzzip. Thwok bwom vrooaaaa bam pow screeeeam kaboom vroom zap snap twak. Crackle whack boom zap wham tonk wallop bwom whack blam gadzooks. Kerplunk screeeeam koom tonk zap crash bwom screeeeam zzzip bam vroom smack pow. Vroom whack wallop crash kerplunk bwom twak pow bwom crash!</p>",
		"<h2><a href=''>HCI theory helps us turn to the wild?</a></h2><p>I'm the Batman. Thwok wallop pow koom zoink twak pok zoink smack zap crack pop zzzip. Thwok bwom vrooaaaa bam pow screeeeam kaboom vroom zap snap twak. Crackle whack boom zap wham tonk wallop bwom whack blam gadzooks. Kerplunk screeeeam koom tonk zap crash bwom screeeeam zzzip bam vroom smack pow. Vroom whack wallop crash kerplunk bwom twak pow bwom crash!</p>",
		"<h2><a href=''>HCI theory helps us actor-network theory something?</a></h2><p>I'm the Batman. Thwok wallop pow koom zoink twak pok zoink smack zap crack pop zzzip. Thwok bwom vrooaaaa bam pow screeeeam kaboom vroom zap snap twak. Crackle whack boom zap wham tonk wallop bwom whack blam gadzooks. Kerplunk screeeeam koom tonk zap crash bwom screeeeam zzzip bam vroom smack pow. Vroom whack wallop crash kerplunk bwom twak pow bwom crash!</p>"
	]
	var randomanswer = answers[ Math.floor(Math.random() * answers.length ) ];

	$("#answer").append( randomanswer );
});